# Generated by Django 5.2.7 on 2025-10-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringAnalysis',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(db_index=True, unique=True)),
                ('length', models.IntegerField(db_index=True)),
                ('is_palindrome', models.BooleanField(db_index=True, default=False)),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField(db_index=True)),
                ('sha256_hash', models.CharField(editable=False, max_length=64)),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'String Analysis',
                'verbose_name_plural': 'String Analyses',
                'db_table': 'string_analysis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['value'], name='string_anal_value_618c97_idx'), models.Index(fields=['is_palindrome'], name='string_anal_is_pali_48ea88_idx'), models.Index(fields=['length'], name='string_anal_length_c136e5_idx'), models.Index(fields=['word_count'], name='string_anal_word_co_d0cb6e_idx')],
            },
        ),
    ]
